// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuHDMXix28Bxdw5tBNoPOumW__2zu3lVc',
    appId: '1:38187875378:web:28c479c0883438a317d02b',
    messagingSenderId: '38187875378',
    projectId: 'iiitm-attendance-system',
    authDomain: 'iiitm-attendance-system.firebaseapp.com',
    storageBucket: 'iiitm-attendance-system.firebasestorage.app',
    measurementId: 'G-546NVFRQSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvAloyyORgGAICXNRxggaeFqpKQMv7rJ4',
    appId: '1:38187875378:android:7a5350e3fc26170c17d02b',
    messagingSenderId: '38187875378',
    projectId: 'iiitm-attendance-system',
    storageBucket: 'iiitm-attendance-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCupoNzUzaY7zvfQwKB1CGyBOTChzpSv-Y',
    appId: '1:38187875378:ios:26ce6d04c3b01b5717d02b',
    messagingSenderId: '38187875378',
    projectId: 'iiitm-attendance-system',
    storageBucket: 'iiitm-attendance-system.firebasestorage.app',
    iosClientId: '38187875378-fblpl6cjg3steo47skmfji77mro72d6i.apps.googleusercontent.com',
    iosBundleId: 'com.aishtrex.attendance.attendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCupoNzUzaY7zvfQwKB1CGyBOTChzpSv-Y',
    appId: '1:38187875378:ios:26ce6d04c3b01b5717d02b',
    messagingSenderId: '38187875378',
    projectId: 'iiitm-attendance-system',
    storageBucket: 'iiitm-attendance-system.firebasestorage.app',
    iosClientId: '38187875378-fblpl6cjg3steo47skmfji77mro72d6i.apps.googleusercontent.com',
    iosBundleId: 'com.aishtrex.attendance.attendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuHDMXix28Bxdw5tBNoPOumW__2zu3lVc',
    appId: '1:38187875378:web:182c82d46c7d7a3c17d02b',
    messagingSenderId: '38187875378',
    projectId: 'iiitm-attendance-system',
    authDomain: 'iiitm-attendance-system.firebaseapp.com',
    storageBucket: 'iiitm-attendance-system.firebasestorage.app',
    measurementId: 'G-H208N3HDSF',
  );

}